from menus.menu_worker import MenuWorker
'''
ESTO ES UNA APP DE CONSOLA PARA CALCULAR PROBABILIDADES Y ESTADÍSTICAS CREADA PARA AFIANZAR CONOCIMIENTOS DE PYTHON
Y DE LAS DIFERENTES OPERACIONES DE ESTADISTICA Y PROBABILIDAD, ALGUNAS OPERACIONES NO USAN LA FORMA MAS OPTIMA SI NO,
EN SU LUGAR UNA MANERA MAS VISUAL DE REPRESENTAR LAS FORMULAS Y OPERACIONES, GENERALMENTE SI HAY CASOS QUE CONOZCO
DE HACERLO MAS OPTIMO SE DEJARAN EN EL COMENTARIO DE LA SUSODICHA OPERACION.
'''
while (True):
    _menu = MenuWorker()
    _rtr = _menu.start_menu()
    if _rtr == 3:
        break